spring: 
  profiles:
    active:
    - dev
---
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-donald-dev
---
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-donald-test